import { Geist, Geist_Mono,DM_Sans } from "next/font/google";
import Providers from "./providers";
import "./globals.css";
import localFont  from 'next/font/local'

const abcgintonord = localFont({
  src: [
    {
      path: '../public/fonts/abcgintonord.woff',
      weight: '800',
      style: 'normal'
    }
  ],
  variable: '--font-abcgintonord'
})

const ggSans = localFont({
  src: [
    {
      path: '../public/fonts/ggSans.woff',
      style: 'normal'
    }
  ],
  variable: '--font-ggsans'
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Discord Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dmSans.className} ${abcgintonord.variable} ${ggSans.variable} `}
        suppressHydrationWarning
      >
        <Providers session={session}>
          {children}
        </Providers>
      </body>
    </html>
  );
}
